2023-10-13 07:32:36 | INFO    | __main__:from_epic:40 | run - {'stage': 'Initialization EpicPlayer'}
2023-10-13 07:32:40 | INFO    | __main__:claim_epic_games:86 | Try to flush cookie - {'task': 'claim_epic_games'}
2023-10-13 07:32:41 | SUCCESS    | services.agents.epic_games:_login:129 | login - {'result': 'token has not expired'}
2023-10-13 07:32:49 | SUCCESS    | services.agents.epic_games:flush_token:150 | flush_token - {'path': PosixPath('/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/user_data_dir/epic-games@derrors.li/ctx_cookie.json')}
2023-10-13 07:32:50 | WARNING    | services.agents.epic_games:get_order_history:301 | Failed to get order history, cookie may have expired - {}
2023-10-13 07:32:51 | ERROR    | __main__:run:126 | An error has been caught in function 'run', process 'MainProcess' (3909), thread 'MainThread' (140356472011840): - {}
Traceback (most recent call last):
  File "/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/src/claim.py", line 130, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/src/claim.py", line 126, in run
    await agent.stash()
  File "/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/src/claim.py", line 120, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/src/claim.py", line 95, in claim_epic_games
    self.create_tasks()
  File "/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/src/claim.py", line 53, in create_tasks
    self._pros = get_promotions()
  File "/home/runner/work/Epic-Free-Games/Epic-Free-Games/epic/src/services/agents/epic_games.py", line 261, in get_promotions
    query = promotion["catalogNs"]["mappings"][0]["pageSlug"]
TypeError: 'NoneType' object is not subscriptable
